### ISSUE TITLE
[Redmine 3.3] Internal Error on TimeTracker Link

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [hicknhack-software/redmine_time_tracker#209]
On the left top menu there is a Time Tracker Link but it results just in an Internal error.
The logfile writes:
Completed 500 Internal Server Error in 320ms (ActiveRecord: 18.1ms)
NoMethodError (undefined method strip' for ["time_logs.started_on DESC"]:Array): plugins/redmine_time_tracker/app/models/time_log_query.rb:59:inlogs'
plugins/redmine_time_tracker/app/controllers/tt_overview_controller.rb:35:in index' lib/redmine/sudo_mode.rb:63:insudo_mode'

**Comment by jume-dev** [comment]
I am not sure what you are doing, but we use the time tracker everyday without problems.

Do you have everything correctly installed? Which redmine and plugin version do you use?

**Comment by Sh4d0wF1gh7** [comment]
Installation Process without problems. Also usage is ok. Just the top link.
I use the Circle Template but also on f.e. Abacus Office Theme same error.
Installed and working Plugins are:
Advanced roadmap & milestones
Clipboard image paste
Event Notifications
Redmine Agile Light Version
Redmine Code Review
Redmine Helpdesk
Redmine Local Avatars
Redmine Time Tracker
Unread Issues

**Comment by Sh4d0wF1gh7** [comment]
Redmine 3.3.0 auf einem Debian 7 mit Apache2

**Comment by Sh4d0wF1gh7** [comment]
Hello again,
i looked @ Google for the error "NoMethodError undefined method strip" and found many entries but until yet no solution for me?
I tested different templates but also without success.
I use current stable releases with listed Plugins?
Where i can search further?

**Comment by Sh4d0wF1gh7** [comment]
Do you know about this error specially with redmine 3.3.0?
Also today i looked in the source code but cannot find any solutions according namend NoMethodError Undefined Methot "Strip"

**Comment by jume-dev** [comment]
Alright, i took a look and it seems like our timetracker is not compatible with redmine 3.3 because they changed some things in the query class. Sadly i won't have time to fix this. If you are familar with ruby take a look, pull request are very welcome.

Otherwise maybe try the rewrite branch and see if this works for you. But be careful, it changes the data format so you should definitly make a backup before trying it out. If you settle with it, you can convert your old time entries in the settings of the plugin

**Comment by jume-dev** [comment]
Should be working now thanks to quexpl
